version: '3'

services:
  database:
    container_name: fskogni_nextcloud_database
    image: postgres:14-alpine
    env_file:
      # another account for nextcloud is created, config can be found in the config.php in the config folder in nextcloud volume
      - .env_database
    volumes:
      - /srv/data/fskogni/nextcloud/database:/var/lib/postgresql/data
    restart: always
  app:
    container_name: fskogni_nextcloud_container
    image: nextcloud:25
    volumes:
      - /srv/data/fskogni/nextcloud/data:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/zzz-custom.ini
    environment:
      - APACHE_DISABLE_REWRITE_IP=1
      - OVERWRITEWEBROOT=/cloud
      - TRUSTED_PROXIES=10.0.0.0/8 192.168.0.0/16 172.16.0.0/12
    restart: always
    depends_on:
      - database
  nginx:
    container_name: fskogni_nextcloud_nginx
    image: fsinf/nginx:latest
    ports:
      - 8469:80
    volumes:
      - /srv/data/fskogni/nextcloud/data:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-nextcloud.conf:/etc/nginx/sites-enabled/nginx-nextcloud.conf
      - /srv/docker/shared/nginx/security-headers.conf:/etc/nginx/shared/security-headers.conf:ro
    restart: always
