version: '3.6'
services:
  database:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=hedgedoc
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=hedgedoc
    volumes:
      - /srv/data/fskogni/hedgedoc/database:/var/lib/postgresql/data
    restart: always

  app:
    image: quay.io/hedgedoc/hedgedoc:1.9.6
    container_name: fskogni_pad_container
    environment:
      - CMD_DOMAIN=www.fs-kogni.uni-tuebingen.de
      - CMD_URL_PATH=pad
      - CMD_USECDN=false
      - CMD_PROTOCOL_USESSL=true
      - CMD_USESSL=false
      - CMD_DB_URL=${CMD_DB_URL}
      - CMD_OAUTH2_USER_PROFILE_URL=https://aai.fsi.uni-tuebingen.de/auth/realms/fskogni_account/protocol/openid-connect/userinfo
      - CMD_OAUTH2_USER_PROFILE_USERNAME_ATTR=preferred_username
      - CMD_OAUTH2_USER_PROFILE_DISPLAY_NAME_ATTR=name
      - CMD_OAUTH2_USER_PROFILE_EMAIL_ATTR=email
      - CMD_OAUTH2_SCOPE=openid
      - CMD_OAUTH2_TOKEN_URL=https://aai.fsi.uni-tuebingen.de/auth/realms/fskogni_account/protocol/openid-connect/token
      - CMD_OAUTH2_AUTHORIZATION_URL=https://aai.fsi.uni-tuebingen.de/auth/realms/fskogni_account/protocol/openid-connect/auth
      - CMD_OAUTH2_CLIENT_ID=hedgedoc
      - CMD_OAUTH2_PROVIDERNAME=FSKogni SSO
      - CMD_OAUTH2_ROLES_CLAIM=groups
      - CMD_OAUTH2_ACCESS_ROLE=hedgedoc
      - CMD_EMAIL=false
      - CMD_URL_ADDPORT=false
      - CMD_ALLOW_GRAVATAR=false
      - CMD_ALLOW_ANONYMOUS=false
      - CMD_ALLOW_ANONYMOUS_EDITS=true
      - CMD_ALLOW_FREEURL=true
      - CMD_DEFAULT_PERMISSION=limited
      - CMD_ALLOW_PDF_EXPORT=true
      - CMD_SESSION_LIFE=2592000000
      - NODE_EXTRA_CA_CERTS=/etc/ssl/certs/ISRG_Root_X1.pem
      - CMD_COOKIE_POLICY=strict
    volumes:
      - /srv/data/fskogni/hedgedoc/uploads:/hedgedoc/public/uploads
      - /etc/ssl/certs:/etc/ssl/certs:ro
      - /usr/local/share/ca-certificates:/usr/local/share/ca-certificates:ro
    restart: always
    depends_on:
      - database

  nginx:
    image: fsinf/nginx:latest
    container_name: fskogni_hedgedoc_nginx
    ports:
      - "134.2.220.61:8470:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-codimd.conf:/etc/nginx/sites-enabled/nginx-codimd.conf:ro
      - /srv/docker/shared/nginx/security-headers.conf:/etc/nginx/shared/security-headers.conf:ro
    restart: always
