version: "3"

services:
    nginx:
        image: fsinf/nginx:latest
        ports:
            - "134.2.220.61:8770:443"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx-eei.conf:/etc/nginx/sites-enabled/nginx-eei.conf:ro
            - /srv/data/eei/git:/var/www/html:ro
            - /srv/docker-certificates/eei.fsi.uni-tuebingen.de/:/etc/nginx/ssl:ro
            - /srv/docker/shared/nginx/:/etc/nginx/shared/:ro
        links:
            - php
        restart: always
        depends_on:
            php:
                condition: service_healthy
        healthcheck:
            test: ["CMD", "curl", "-f", "https://eei.fsi.uni-tuebingen.de/_nginx_health"]
            interval: 30s
            timeout: 2s
            retries: 2
            start_period: 10s

    php:
        image: php:8.1-fpm-alpine
        user: www-data
        volumes:
            - /srv/data/eei/eei-registration:/var/www/eei-registration
            - /srv/data/eei/git:/var/www/html:ro
        restart: always
        healthcheck:
            test: ["CMD-SHELL", "pgrep php-fpm && php healthcheck.php && php index.php"]
            interval: 1m
            timeout: 2s
            retries: 2
            start_period: 10s
