version: "2"

services:
  server:
    container_name: gitea_server
    image: gitea/gitea:1
    env_file:
      - .env_server
    restart: always
    networks:
      backend:
        ipv4_address: 10.0.3.5
    volumes:
      - /srv/data/gitea/data:/data
    ports:
      - "222:22"
    depends_on:
      - db

  db:
    container_name: gitea_db
    image: postgres:13-alpine
    restart: always
    env_file:
      - .env_database
    networks:
      backend:
        ipv4_address: 10.0.3.4
    volumes:
      - /srv/data/gitea/database:/var/lib/postgresql/data

  nginx:
   image: fsinf/nginx:latest
   container_name: gitea_nginx
   ports:
     - "134.2.220.61:8200:443"
   volumes:
     - /srv/docker-certificates/git.fsi.uni-tuebingen.de/:/etc/nginx/ssl:ro
     - /srv/docker-certificates/git.fsi.uni-tuebingen.de_ecc/:/etc/nginx/ssl-ecc:ro
     - ./nginx.conf:/etc/nginx/nginx.conf:ro
     - ./nginx-gitea.conf:/etc/nginx/sites-enabled/nginx-codimd.conf:ro
     - /srv/docker/shared/nginx/ssl.conf:/etc/nginx/shared/ssl.conf:ro
     - /srv/docker/shared/nginx/security-headers.conf:/etc/nginx/shared/security-headers.conf:ro
   networks:
     backend:
       ipv4_address: 10.0.3.2
   restart: always

networks:
  backend:
    ipam:
      config:
        - subnet: 10.0.3.0/24

