version: '3'

services:
  postgres:
    image: postgres:14
    volumes:
      - /srv/data/keycloak/database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U",  "keycloak"]
      interval: 30s
      timeout: 2s
      retries: 2
      start_period: 10s

  keycloak:
    image: fsinf/keycloak:latest
    build: .
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_DATABASE=keycloak
      - KC_DB_USER=keycloak
      - KC_DB_SCHEMA=public
      - KC_DB_PASSWORD=${POSTGRES_PASSWORD}
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - PROXY_ADDRESS_FORWARDING='true'
      - KC_HTTP_ENABLED='true'
      - KC_HTTP_PORT=8080
      - KC_HOSTNAME=aai.fsi.uni-tuebingen.de
      - KC_HOSTNAME_STRICT='false'
      - KC_HTTPS_PORT=443
      - KC_PROXY=edge
    volumes:
      - /srv/data/keycloak/data:/data
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: /opt/keycloak/bin/kc.sh start --optimized --spi-connections-jpa-legacy-migration-strategy=update
    restart: always
    healthcheck:
      # https://github.com/keycloak/keycloak/issues/17273#issuecomment-1693549331
      test: grep -q '00000000:1F90 00000000:0000' /proc/net/tcp
      interval: 30s
      timeout: 2s
      retries: 2
      start_period: 30s

  nginx:
    container_name: keycloak_nginx
    image: fsinf/nginx:latest
    ports:
      - 9041:443
    volumes:
      - /srv/docker-certificates/aai.fsi.uni-tuebingen.de/:/etc/nginx/ssl:ro
      - /srv/docker-certificates/aai.fsi.uni-tuebingen.de_ecc/:/etc/nginx/ssl-ecc:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-keycloak.conf:/etc/nginx/sites-enabled/nginx-keycloak.conf
      - /srv/docker/shared/nginx/:/etc/nginx/shared/:ro
      - ./index.html:/var/www/keycloak/index.html
    restart: always
    depends_on:
      keycloak:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "https://aai.fsi.uni-tuebingen.de/_nginx_health"]
      interval: 30s
      timeout: 2s
      retries: 2
      start_period: 10s