version: "3.8"

networks:
  backend:
    ipam:
      config:
        - subnet: 10.0.1.0/24
          gateway: 10.0.1.1


services:
  database:
    container_name: nextcloud_database
    image: postgres:14-alpine
    env_file:
      # another account for nextcloud is created, config can be found in the config.php in the config folder in nextcloud volume
      - .env_database
    volumes:
      - /srv/data/nextcloud/database:/var/lib/postgresql/data
    networks:
      backend:
        ipv4_address: 10.0.1.3
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U",  "${POSTGRES_USER}"]
      interval: 30s
      timeout: 2s
      retries: 2
      start_period: 10s

  app:
    container_name: nextcloud_container
    build: ./docker/27/apache/
    image: git.fsi.uni-tuebingen.de/gitea_container-registry/nextcloud:stable
    environment:
      - REDIS_HOST=10.0.1.6
    volumes:
      - /srv/data/nextcloud/data:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/zzz-custom.ini
    restart: always
    depends_on:
      - database
    networks:
      backend:
        ipv4_address: 10.0.1.2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/status.php"]
      interval: 30s
      timeout: 1s
      retries: 2
      start_period: 10s

  nginx:
    container_name: nextcloud_nginx
    image: fsinf/nginx:latest
    ports:
      - "8090:443"
    volumes:
      - /srv/data/nextcloud/data:/var/www/html
      - /srv/docker-certificates/cloud.fsi.uni-tuebingen.de/:/etc/nginx/ssl:ro
      - /srv/docker-certificates/cloud.fsi.uni-tuebingen.de_ecc/:/etc/nginx/ssl-ecc:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-nextcloud.conf:/etc/nginx/sites-enabled/nginx-nextcloud.conf
      - /srv/docker/shared/nginx/ssl.conf:/etc/nginx/shared/ssl.conf:ro
      - /srv/docker/shared/nginx/security-headers.conf:/etc/nginx/shared/security-headers.conf:ro
    restart: always
    networks:
      backend:
        ipv4_address: 10.0.1.4
    healthcheck:
      test: ["CMD", "curl", "-f", "https://cloud.fsi.uni-tuebingen.de/status.php"]
      interval: 30s
      timeout: 1s
      retries: 2
      start_period: 10s

  redis:
    container_name: nextcloud_redis
    image: redis:latest
    deploy:
      resources:
        limits:
          memory: 2g
    restart: always
    mem_limit: 2048M
    networks:
      backend:
        ipv4_address: 10.0.1.6
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 1s
      retries: 2
      start_period: 10s
