version: '3'

services:
  database:
    container_name: fskogni_wordpress_database
    image: mariadb:lts
    env_file:
      - .env_database
    volumes:
      - /srv/data/fskogni/wordpress/database:/var/lib/mysql
      # also see wordpress/docker-compose.yml#L18 @ 028a91674e153aa2b70192432342f723270a53c2
      - /srv/data/fskogni/wordpress/database_git:/var/database_git
      - ./.my-healthcheck.cnf:/healthcheck.cnf
    restart: always
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--defaults-extra-file=healthcheck.cnf", "--connect", "--innodb_initialized" ]
      interval: 30s
      timeout: 2s
      retries: 2
      start_period: 10s

  wordpress:
    container_name: fskogni_wordpress_container
    image: fsinf/wordpress-fpmalpine-apcu-wpcli
    build: ../wordpress/
    volumes:
      - /srv/data/fskogni/wordpress/data:/var/www/html
      - ./upload.ini:/usr/local/etc/php/conf.d/uploads.ini
    restart: always
    env_file:
      - .env_wordpress
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "pgrep", "php-fpm"]
      interval: 30s
      timeout: 2s
      retries: 2
      start_period: 10s

  nginx:
    container_name: fskogni_wordpress_nginx
    image: fsinf/nginx:latest
    ports:
      - 8468:80
    volumes:
      - /srv/data/fskogni/wordpress/data:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-wordpress.conf:/etc/nginx/sites-enabled/nginx-wordpress.conf
      - ./fastcgi_params:/etc/nginx/fastcgi_params
      - /srv/docker/shared/nginx/:/etc/nginx/shared/:ro
    restart: always
    depends_on:
      wordpress:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-I", "-f", "http://localhost/_nginx_health"]
      interval: 30s
      timeout: 2s
      retries: 2
      start_period: 10s