version: '2'
services:
  proxy:
    container_name: http-redir
    build: .
    image: 'fsinf/http-redir:latest'
    restart: always
    ports:
            - '134.2.220.61:8100:80'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://cloud.fsi.uni-tuebingen.de/_nginx_health"]
      interval: 30s
      timeout: 2s
      retries: 2
      start_period: 10s